post http://127.0.0.1:3000/notify
Content-Type: application/json

{
    "message": "Hello, this is a test message!"
}
####
post https://baily.at/notify
Content-Type: application/json

{
    "message": "Hello, this is a test message!"
}